version: '3.8'

services:
  django:
    build: .
    env_file:
      - .env
    command: > 
      bash -c "
        cd src &&
        poetry run python manage.py migrate &&
        poetry run python manage.py collectstatic --noinput &&
        cp -r /app/src/collected_static/. /backend_static &&
        cp -r /app/src/static/. /backend_static &&
        poetry run gunicorn --bind 0.0.0.0:8000 family_finances.wsgi
      "
    volumes:
      - ff2_static:/backend_static
    networks:
      - ff2_network
    restart: always

  gateway:
    build: nginx/.
    env_file: .env
    depends_on:
      - django
    volumes:
      - ff2_static:/static/
    networks:
      - ff2_network
    ports:
      - "9000:80"
    restart: always

volumes:
  ff2_static:

networks:
  ff2_network:
