apiVersion: v1
kind: ConfigMap
metadata:
  name: ff2-nginx-config
  namespace: default
data:
  default.conf: |
    server {
      listen 80;
      location /static/ {
        alias /static/;
      }
    }

