apiVersion: v1
kind: Service
metadata:
  name: ff2-nginx-service
  labels:
    app: ff2-nginx
spec:
  selector:
    app: ff2-nginx
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 
  type: ClusterIP 

