apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ff2-static
  name: ff2-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
