# Generated by Django 5.1.3 on 2024-12-05 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedusertospace',
            name='linked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='linked_users',
            field=models.ManyToManyField(through='transactions.LinkedUserToSpace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkedusertospace',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.space'),
        ),
        migrations.AddField(
            model_name='summary',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.space'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.space'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_name_user'),
        ),
        migrations.AddConstraint(
            model_name='linkedusertospace',
            constraint=models.UniqueConstraint(fields=('space', 'linked_user'), name='unique_space_linked_user'),
        ),
        migrations.AddConstraint(
            model_name='summary',
            constraint=models.UniqueConstraint(fields=('space', 'period_month', 'period_year', 'group_name'), name='unique_summary_group_name'),
        ),
    ]
