# Generated by Django 5.1.4 on 2024-12-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_space_linked_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='linked_chat',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
