# Generated by Django 5.1.3 on 2026-05-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_space_linked_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedusertospace',
            name='role',
            field=models.CharField(choices=[('view_space', 'Просмотр'), ('edit_space', 'Редактирование')], default='view_space', max_length=20),
        ),
    ]
