# Generated by Django 5.1.4 on 2024-12-17 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
        ('users', '0002_alter_coresettings_current_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coresettings',
            name='current_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.space'),
        ),
    ]
