# Generated by Django 5.1.4 on 2024-12-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_coresettings_current_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsettings',
            name='joint_chat',
        ),
    ]
