name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REPO: ivanovdv/ff2-django

jobs:
  tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.8.4
    - name: Install dependencies
      run: poetry install --with dev
    - name: Flake8 and tests
      env:
        POSTGRES_USER: django_user
        POSTGRES_PASSWORD: django_password
        POSTGRES_DB: django_db
        POSTGRES_HOST: 127.0.0.1
        POSTGRES_PORT: 5432
        ACCESS_TOKEN: qwerty123456
      run: |
        poetry run flake8
        poetry run pytest


  deploy_via_k8s:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_REPO:latest .
          docker push $DOCKER_REPO:latest

      - name: Set up kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl version --client
          kubectl delete job django-collectstatic --ignore-not-found
          kubectl apply -f k8s/
          kubectl rollout restart deployment ff2-django
          kubectl rollout restart deployment ff2-nginx

      - name: Wait for static Job to complete
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl wait --for=condition=complete --timeout=180s job/django-collectstatic
